### ISSUE TITLE
RSocket Java SDK 1.1.1:  Operator called default onErrorDropped

### ISSUE THREAD

**Issue by linux-china** [rsocket/rsocket-java#1018]
After introduce RSocket Java  SDK from 1.1.0 to  1.1.1, a simple server will throw exception after client disconnected. 

```java
public class RSocketResponderApp {
    public static void main(String[] args) throws Exception {
        CloseableChannel closeableChannel = RSocketServer.create()
                .acceptor((setup, sendingSocket) -> {
                    return Mono.just(new RSocket() {
                        @Override
                        public Mono<Payload> requestResponse(Payload payload) {
                            return Mono.just(payload);
                        }
                    });
                })
                .bind(TcpServerTransport.create("0.0.0.0", 42252))
                .block();
        System.out.println("RSocket responder is listening on 42252!");
        closeableChannel.onClose().block();
    }
}
```

Exception on server side by `rsc --request --route=xxxx --data=Foo --debug tcp://localhost:42252` 

```
15:42:58.383 [ERROR] r.c.p.Operators - Operator called default onErrorDropped
java.util.concurrent.CancellationException: Disposed
	at io.rsocket.internal.UnboundedProcessor.dispose(UnboundedProcessor.java:550)
	at io.rsocket.transport.netty.TcpDuplexConnection.doOnClose(TcpDuplexConnection.java:67)
	at io.rsocket.internal.BaseDuplexConnection.lambda$new$0(BaseDuplexConnection.java:30)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.runFinally(FluxDoFinally.java:163)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:146)
	at reactor.core.publisher.SinkEmptyMulticast$VoidInner.onComplete(SinkEmptyMulticast.java:227)
	at reactor.core.publisher.SinkEmptyMulticast.tryEmitEmpty(SinkEmptyMulticast.java:70)
	at reactor.core.publisher.SinkEmptySerialized.tryEmitEmpty(SinkEmptySerialized.java:43)
	at io.rsocket.internal.BaseDuplexConnection.dispose(BaseDuplexConnection.java:51)
	at io.rsocket.transport.netty.TcpDuplexConnection.lambda$new$0(TcpDuplexConnection.java:49)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1186)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:773)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:749)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:105)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:174)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Wrapped by: reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.concurrent.CancellationException: Disposed
```

On the requester's side,  after `rsocket.dispose()` and above exception will be thrown.

**Comment by OlegDokuka** [comment]
hey @linux-china!

That is should not be harmful and can be disabled with `Hooks.onErrorDropped(() -> {})`
Do you think it is noisy? We can improve it for sure.

Best,
Oleh

**Comment by linux-china** [comment]
I think it's some noisy. If a new guy wants to try the demo, and he will think the exception as error.   Even we have the document about `Hooks.onErrorDropped(() -> {})` and I think he will not try to check the document.

**Comment by making** [comment]
Is this behavior due to the client(`rsc`)'s misbehavior? Or is it a server-side thing?

**Comment by OlegDokuka** [comment]
should be fixed with https://github.com/rsocket/rsocket-java/commit/1f7191456f2961d1d29f682fb609c7d0783ef9a2

**Comment by Blockost** [comment]
I'm still seeing the stacktrace in `rsocket-core@1.1.1`. In which release is this supposed to have been fixed ? 🤔

**Comment by OlegDokuka** [comment]
it is fixed with 1.1.2 wich is not yet released

**Comment by mkrzywanski** [comment]
I have upgraded to `1.1.2` manually but I get same exception upon cancelling the the rsocket `channel` flux from my tests. https://github.com/mkrzywanski/rsocket-reactive-chat/blob/1dc6b6835b1e05c29049c04e85207847a53e3f59/chat-backend/src/test/java/io/mkrzywanski/chat/app/MessageControllerTest.java#L123. I am not sure if this is same issue as described here or I am doing something else wrong.

**Comment by OlegDokuka** [comment]
@mkrzywanski it is a different one. Feel free to create a separate issue with the mentioned reproducer
